-- EmoteManager.lua
-- Written by Almagnus1 edited by Exopan 
-- Handles emote lookup and alias string creation



function EmoteManager(number) -- Main Function for Emote creation
	locale = Turbine.Engine.GetLanguage();
	if locale == 0 or locale == 268435457 then
		emotes =
		{
			"faint",		-- 1
			"story",
			"no",
			"mumble",
			"look",			-- 5
			"smoke",
			"dance",
			"rude",
			"cower",
			"pat",			-- 10
			"shrug",
			"surrender",
			"mock",
			"kneel",
			"sad",			-- 15
			"angry",
			"stare",
			"cry",
			"sorry",
			"impatient",	-- 20
			"bye",
			"handstand",
			"thank",
			"whistle",
			"blush",		-- 25
			"flirt",
			"nothing",
			"away",
			"beg",
			"fight",		-- 30
			"hug",
			"sing",
			"mourn",
			"assist",
			"crazy",		-- 35
			"liedown",
			"laugh",
			"bored",
			"sit",
			"mood_sleepy",	-- 40
			"eat",
			"stretch",
			"bow",
			"wave",
			"shiver",		-- 45
			"sigh",
			"clap",
			"pose",
			"poke",
			"drool",		-- 50
			"ready",
			"calm",
			"agree",
			"salute",
			"cheer",		-- 55
			"pick",
			"charge",
			"slap",
			"sweat",
			"drink",		-- 60
			"wink",
			"roar",
			"scratch",
			"tear",
			"scold",		-- 65
			"yawn",
			"talk",
			"challenge",
			"bother",
			"pushups",		-- 70
			"curtsey",
			"cough",
			"point",
			"flip",
			"wait",			-- 75
			"beckon",
			"yes",
			"grumble",
			"kiss",
			"think",		-- 80
			"hail",
			"innocent",
			"shakefist"
		};
	elseif locale == 268435460 then
		emotes =
		{
			"ohnmacht",
			"geschichte",
			"nein",
			"murmeln",
			"schauen",
			"rauchen",
			"tanzen",
			"unhöflich",
			"stimmung-ängstlich",
			"tätscheln",
			"achselzucken",
			"aufgeben",
			"verspotten",
			"niederknien",
			"traurig",
			"wütend",
			"anstarren",
			"heul",
			"entschuldigen",
			"ungeduldig",
			"tschüss",
			"handstand",
			"danken",
			"pfeifen",
			"erröten",
			"flirten",
			"nichts",
			"weg",
			"flehen",
			"streiten",
			"umarmen",
			"singen",
			"trauern",
			"beistand",
			"verrückt",
			"hinlegen",
			"lol",
			"gelangweilt",
			"sitzen",
			"ausruhen",
			"essen",
			"strecken",
			"verbeugen",
			"winken",
			"erschauern",
			"seufz",
			"applaudieren",
			"posieren",
			"knuffen",
			"lechzen",
			"bereit",
			"beruhigen",
			"zustimmen",
			"salutieren",
			"jubeln",
			"pokratzen",
			"angreifen",
			"ohrfeige",
			"schwitzen",
			"trinken",
			"zwinkern",
			"brüllen",
			"kratzen",
			"träne",
			"ausschimpfen",
			"gähnen",
			"sprechen",
			"herausfordern",
			"belästigen",
			"liegestütze",
			"knicksen",
			"hüsteln",
			"zeigen",
			"salto",
			"warten",
			"heranwinken",
			"ja",
			"motzen",
			"küssen",
			"nachdenken",
			"gruß",
			"unschuldig",
			"faustschütteln"
		};		
	elseif locale == 268435459 then -- needs to be tested
		emotes =
		{
			"défaillir",
			"histoire",
			"non",
			"marmonner",
			"regarder",
			"fumer",
			"danser",
			"malpoli",
			"humeur_crainte",
			"tape",
			"épaules",
			"abandonner",
			"railler",
			"genou",
			"humeur_triste",
			"colère", 
			"regarder",
			"pleurs", 
			"pardon",
			"impatient", 
			"au_revoir", 
			"équilibre", 
			"merci",
			"siffler",
			"rougir",
			"flirter",
			"rien",
			"absent", 
			"supplier",
			"attaquer",
			"serrer",
			"chanter",
			"deuil",
			"aider",
			"fou",
			"allonger",
			"rire",
			"ennui",
			"asseoir",
			"repos",
			"manger", 
			"étirer", 
			"incliner",
			"coucou", 
			"frissonner",
			"soupir", 
			"applaudir", 
			"poser",
			"pincer", 
			"baver",
			"prêt",
			"calmer",
			"accord", 
			"saluer", 
			"bravo",
			"démanger",
			"charger",
			"gifler", 
			"transpirer",
			"boire",
			"cligner",
			"rugir",
			"gratter",
			"larme", 
			"gronder",
			"bâiller",
			"discuter",
			"défi",
			"enquiquiner",
			"pompes", 
			"révérence", 
			"tousser",
			"désigner",
			"sauter",
			"attendez",
			"appeler",
			"oui",
			"ronchonner",
			"bise",
			"réfléchir",
			"bonjour",
			"innocent",
			"poing"
		};
	else -- sry russian clients...
		emotes =
		{
			"faint",		-- 1
			"story",
			"no",
			"mumble",
			"look",			-- 5
			"smoke",
			"dance",
			"rude",
			"cower",
			"pat",			-- 10
			"shrug",
			"surrender",
			"mock",
			"kneel",
			"sad",			-- 15
			"angry",
			"stare",
			"cry",
			"sorry",
			"impatient",	-- 20
			"bye",
			"handstand",
			"thank",
			"whistle",
			"blush",		-- 25
			"flirt",
			"nothing",
			"away",
			"beg",
			"fight",		-- 30
			"hug",
			"sing",
			"mourn",
			"assist",
			"crazy",		-- 35
			"liedown",
			"laugh",
			"bored",
			"sit",
			"mood_sleepy",	-- 40
			"eat",
			"stretch",
			"bow",
			"wave",
			"shiver",		-- 45
			"sigh",
			"clap",
			"pose",
			"poke",
			"drool",		-- 50
			"ready",
			"calm",
			"agree",
			"salute",
			"cheer",		-- 55
			"pick",
			"charge",
			"slap",
			"sweat",
			"drink",		-- 60
			"wink",
			"roar",
			"scratch",
			"tear",
			"scold",		-- 65
			"yawn",
			"talk",
			"challenge",
			"bother",
			"pushups",		-- 70
			"curtsey",
			"cough",
			"point",
			"flip",
			"wait",			-- 75
			"beckon",
			"yes",
			"grumble",
			"kiss",
			"think",		-- 80
			"hail",
			"innocent",
			"shakefist"
		};
		end

	return emotes[number];
end

-- looks up the emote in the above arrays, and returns the entry value
--function EmoteManager( number )
--	return emotes[number];
--end
